### ISSUE TITLE
Quiz and quest mode displays incorrect screen

### ISSUE THREAD

**Issue by cmsava1897** [ByunLab/staRt-ionic#229] opened 2018-08-15 23:03 UTC
The error appears as shown in the photos attached:
![img_2099](https://user-images.githubusercontent.com/29290645/44177694-fc2e7900-a0bc-11e8-9405-ed5143edf340.PNG)
![img_2101](https://user-images.githubusercontent.com/29290645/44177695-fd5fa600-a0bc-11e8-8b28-c7bb11b09421.PNG)
![img_2102](https://user-images.githubusercontent.com/29290645/44177699-fe90d300-a0bc-11e8-87ed-242eb7976e9c.PNG)

To reproduce the error: 
1) start the app and click on Quiz or Quest Mode
2) Select either word or syllable quiz/quest 
3) For quest mode, any combination of /r/ settings or number of trials results in the error. And it does not matter if the wave is hidden or not. Once Begin Word/Syllable Quest is clicked the attached screens are displayed

**Comment by starakaj** [comment] 2018-08-16 21:50
Can reproduce

**Comment by starakaj** [comment] 2018-08-16 21:51
Doesn't appear to be current master 31a2f332

**Comment by starakaj** [comment] 2018-08-16 22:01
Seems like some CSVs aren't loading correctly. I wonder @jonathan-chin if you forgot to check in some data files?

**Comment by jonathan-chin** [comment] 2018-08-16 22:26
Seems to be just an issue on the Quiz.

Code that made adaptive difficulty work on Quest was not updated for Quiz. Will fix that soon.

**Comment by cmsava1897** [comment] 2018-08-20 16:27
I just updated the app, and I'm still experiencing the same bug

**Comment by jonathan-chin** [comment] 2018-08-20 16:44
that's very strange. @cmsava1897 is this still happening on both Quest and Quiz?

it's not breaking on my simulated end, though I realized there's another bug. My Quiz doesn't show the word. I will fix that tonight.

Can you try sending me your app logs? I think these instructions will help:

https://support.apple.com/kb/PH26441?locale=en_US

**Comment by cmsava1897** [comment] 2018-08-20 21:27
Yeah, its still hapeening on Quest and Quiz. Here are the logs:

default	17:20:58.000000 -0400	staRt	 Apache Cordova native platform version 4.5.3 is starting.

default	17:20:58.000000 -0400	staRt	 Multi-tasking -> Device: YES, App: YES

default	17:20:58.000000 -0400	staRt	 Using UIWebView

default	17:20:58.000000 -0400	staRt	 [CDVTimer][console] 0.364065ms

default	16:20:58.000000 -0500	staRt	 [CDVTimer][handleopenurl] 0.401974ms

default	17:20:58.000000 -0500	staRt	 [CDVTimer][intentandnavigationfilter] 8.613944ms

default	17:20:58.000000 -0500	staRt	 [CDVTimer][gesturehandler] 0.563025ms

default	17:20:58.000000 -0500	staRt	 [CDVTimer][file] 11.826992ms

default	17:20:58.000000 -0500	staRt	 [CDVTimer][universallinks] 5.532980ms

default	17:20:58.000000 -0500	staRt	 Initializing AudioPlugin, saving to dir /var/mobile/Containers/Data/Application/E12DD91E-A9FB-4E61-BF6B-29FAA22350D4/Library/Application Support/recordings

default	17:20:58.000000 -0500	staRt	 [CDVTimer][audioplugin] 2.799034ms

default	17:20:58.000000 -0500	staRt	 [CDVTimer][TotalPluginStartup] 33.663034ms

default	17:20:58.000000 -0500	staRt	 Resetting plugins due to page load.

default	16:21:01.000000 -0500	staRt	 Finished load of: file:///var/containers/Bundle/Application/0579A336-9554-43DA-A712-759A8EAA976D/staRt.app/www/index.html#/profiles

default	17:21:03.000000 -0400	staRt	 BuildInfo init: 0.0092 sec(9157333 nsec): Return

default	16:21:04.000000 -0500	staRt	 TAAE: Setting audio session category to AVAudioSessionCategoryPlayAndRecord

default	17:21:04.000000 -0500	staRt	 TAAE: Audio session initialized (input available, audio route 'iPad Microphone and Speaker') HW samplerate: 22050

default	17:21:05.000000 -0500	staRt	 TAAE: Input status updated (1 channel, non-interleaved, with converter)

default	17:21:05.000000 -0500	staRt	 TAAE: Engine setup

default	17:21:05.000000 -0500	staRt	 TAAE: Buffer duration 0.023, 512 frames (requested 0.023s, 512 frames)

default	17:21:05.000000 -0500	staRt	 TAAE: Starting Engine

default	17:21:05.000000 -0500	staRt	 THREAD WARNING: ['AudioPlugin'] took '988.207031' ms. Plugin should use a background thread.

default	17:21:05.000000 -0500	staRt	 {"currentProfileUUID":"d0879944-bf4e-48c8-8334-4d1ed89abd6f","profiles":[{"name":"CS","age":21,"heightFeet":5,"heightInches":6,"gender":"Male","uuid":"d0879944-bf4e-48c8-8334-4d1ed89abd6f","recordings":[],"targetF3":2077,"lpcOrder":45}]}

default	17:21:05.000000 -0500	staRt	 start app running

default	17:21:05.000000 -0500	staRt	 Logged in as [object Object]

default	17:21:05.000000 -0500	staRt	 TAAE: Changed audio route to iPad Microphone and Speaker

default	17:21:06.000000 -0400	staRt	 Auto Service initialized

default	16:21:06.000000 -0500	staRt	 Session stats tracking initialized

default	17:21:06.000000 -0500	staRt	 ProfilesController here!

default	17:21:06.000000 -0500	staRt	 ProfilesController here!

default	17:21:06.000000 -0500	staRt	 Logged in as [object Object]

default	17:21:06.000000 -0500	staRt	 Gross (but hopefully harmless) hack still at play

default	16:21:07.000000 -0500	staRt	 null

default	17:21:07.000000 -0500	staRt	 null

default	17:21:07.000000 -0500	staRt	 null

default	17:21:07.000000 -0400	staRt	 [{"accountId":"hGhfnM1GQ6RnCESheCy7FJTjYcy1","age":21,"allFreeplayTime":0,"allQuestTime":28324,"allSessionTime":60200,"allTrialsCompleted":0,"allTrialsCorrect":0,"brandNew":false,"creationTimestamp":1534296020487,"firstSessionTimestamp":null,"formalTester":false,"gender":"Male","heightFeet":5,"heightInches":6,"lastLoginTime":1534296047870,"lastLoginTimestamp":1534296020487,"lastSessionTimestamp":null,"nBiofeedbackSessionsCompleted":0,"nFormalTreatmentComplete":0,"nIntroComplete":0,"nLongSessionsCompleted":0,"nNonBiofeedbackSessionsCompleted":0,"nQuestsCompleted":0,"nQuestsInitiated":3,"nSyllableQuizComplete":0,"nTutorialComplete":0,"nWordQuizComplete":0,"name":"CS","percentTrialsCorrect":0,"targetF3":1612,"uuid":"f82effee-01ba-a3f1-82eb-1c51a25cd297"}]

default	17:21:07.000000 -0400	staRt	 [{"accountId":"hGhfnM1GQ6RnCESheCy7FJTjYcy1","age":21,"allFreeplayTime":0,"allQuestTime":28324,"allSessionTime":60200,"allTrialsCompleted":0,"allTrialsCorrect":0,"brandNew":false,"creationTimestamp":1534296020487,"firstSessionTimestamp":null,"formalTester":false,"gender":"Male","heightFeet":5,"heightInches":6,"lastLoginTime":1534296047870,"lastLoginTimestamp":1534296020487,"lastSessionTimestamp":null,"nBiofeedbackSessionsCompleted":0,"nFormalTreatmentComplete":0,"nIntroComplete":0,"nLongSessionsCompleted":0,"nNonBiofeedbackSessionsCompleted":0,"nQuestsCompleted":0,"nQuestsInitiated":3,"nSyllableQuizComplete":0,"nTutorialComplete":0,"nWordQuizComplete":0,"name":"CS","percentTrialsCorrect":0,"targetF3":1612,"uuid":"f82effee-01ba-a3f1-82eb-1c51a25cd297"}]

default	17:21:09.000000 -0400	staRt	 WordsController here!

default	16:21:10.000000 -0500	staRt	 Begin word quest configuration

default	16:21:14.000000 -0500	staRt	 count is now 55

default	18:59:59.000000 -0500	staRt	 count is now 60

default	18:59:59.000000 -0500	staRt	 count is now 65

default	18:59:59.000000 -0500	staRt	 count is now 70

default	18:59:59.000000 -0500	staRt	 count is now 75

default	18:59:59.000000 -0500	staRt	 count is now 80

default	18:59:59.000000 -0500	staRt	 count is now 85

default	18:59:59.000000 -0500	staRt	 count is now 90

default	18:59:59.000000 -0500	staRt	 count is now 95

default	18:59:59.000000 -0500	staRt	 count is now 100

default	16:21:15.000000 -0500	staRt	 TAAE: Warning: render took too long (0.017337s, 74.66% of budget). Expect glitches.

default	16:21:16.000000 -0500	staRt	 Begin Word quest

default	17:21:25.000000 -0400	staRt	 AutoController here!

default	16:21:27.000000 -0500	staRt	 Begin word probe

**Comment by jonathan-chin** [comment] 2018-08-22 14:36
hi @cmsava1897 thanks for the logs. they seem to be ok; no overt warnings.

I just uploaded a new version (1.0.25) that fixed a minor bug that prevented me from using the app. It's a piece of debug code I left in that I was supposed to remove.

I just tested the new version (1.0.25) on my ipad via TestFlight and it works as expected. if after installing 1.0.25 you continue to have issues, can you provide me with: ipad model, ios version. I'm not sure what else could be causing it.

Do you also happen to be local to NYC?

**Comment by cmsava1897** [comment] 2018-08-22 15:29
Hey Jon,

Yeah it’s still happening, which is strange if it’s working on yours. I’m
on Long Island so, only about 45 min from NYC.

iPad model #: FC706LL/A
iOS version: 9.3.5

I know it’s a bit older, so let me know if you think it might be an issue
with my ipad.

Best
Christian

**Comment by jonathan-chin** [comment] 2018-08-22 15:40
The model and ios version shouldn't really matter, but you're two major
updates behind. The current ios version is 11.4.1.

Let me ping some other testers and see what they get.

**Comment by cmsava1897** [comment] 2018-08-22 15:59
Hey Jon,

Okay, my iPad says it’s up to date, but I can try to update iOS.

Christian

**Comment by starakaj** [comment] 2018-09-05 16:40
Following up here. Did you guys ever get to the bottom of this one?

**Comment by jonathan-chin** [comment] 2018-09-05 17:41
Nope. I think it is specific to Christian's setup. I need to see his physical device to proceed.

**Comment by cmsava1897** [comment] 2018-09-05 17:51
Hi,

Unfortunately, I’m back in Boston for school, so I can’t meet you to look
at the setup of my device. Is there a way we can figure it out remotely?

Christian

**Comment by jonathan-chin** [comment] 2018-09-05 17:55
I can try to walk you through it via Skype. It is a bit technical. Maybe I can control your machine remotely.

**Comment by starakaj** [comment] 2018-09-12 16:49
Hey all, just checking up on this. So one potentially useful data point: @cmsava1897  is using a 3rd generation iPad, which unfortunately won't update past iOS 9. I don't know if this is the cause of the bug, but it at least means that we can't really worry about updating to iOS 11. Also, this makes it hard for us to test on our end, since getting this older version of iOS running requires an older version of xcode.

Still, @cmsava1897, if you have time for a skype, I could show you how to get the developer console open, which would help us get more information. What's your availability tomorrow or next week?

**Comment by starakaj** [comment] 2018-10-02 20:16
Gonna close this one out. If it keeps popping up we can reopen

**Closed by starakaj** 2018-10-02 20:16 UTC
Labels: bug
