### ISSUE TITLE
"Visit Website" link not working

### ISSUE THREAD

**Issue by erinmdoty** [ByunLab/staRt-ionic#310] opened 2018-12-03 17:58 UTC
When creating a new profile, if you click on "formal testing" a prompt comes up titled "formal research pilot" that asks if you want to participate as a formal pilot tester. If you click "yes" or "no" an appropriate prompt comes up, but if you click on "visit website" in this prompt, nothing happens.

![img_0055](https://user-images.githubusercontent.com/42744629/49391915-fc4d9580-f6fa-11e8-8e78-4e5e34a80025.PNG)

Running version 1.0.31 of staRt on iPad 4th generation (AI1458) with iOS 10.3.3

**Comment by helencarey** [comment] 2019-06-19 20:27
This is working for me. @Tjc10  do you want to double-check it on an older iPad?
If its working for you, go ahead and close the issue.

**Comment by Tjc10** [comment] 2019-08-19 22:57
In terms of this issue @helencarey, I am using 2.0.10 (not sure if this matters).  I created a test profile "tc" and when I attempt formal testing and clicked only on the "Visit Website" option, nothing happens for me either.  I exited and re-entered the app. Tried to begin testing again under "tc" profile, formal tester>Visit Website only.  Still nothing happens.

**Comment by helencarey** [comment] 2019-08-20 01:57
Thanks, TJC. I'll look into this.

**Comment by helencarey** [comment] 2019-08-20 17:01
Not quite sure what’s going on here. It seems like it might be Cordova whitelisting thing
https://cordova.apache.org/docs/en/latest/guide/appdev/whitelist/index.html#ios-whitelisting

cordova.InAppBrowser-style linking is working for links in Resources, but it is not working for window.open() from within the $cordovaDialogs.alert() pop-up in the case above.

Code to debug is at _promptForFormalParticipation() on line 573 of common-components/auto-service/auto-service_module.
(called from profiles_controller. template: states/root/profiles/card-templates/card-profile.html)

**Comment by jonathan-chin** [comment] 2019-08-20 19:25
I believe this was caused by the inapp browser plugin not being included. I assume newer versions of iOS handle external links fine, but the plugin is needed for older versions, like 10.3.1. commit 1a9155c should fix this.

**Comment by helencarey** [comment] 2019-08-30 16:20
**Checkpoints for QA**
See Erin's initial bug report at the top of the page.

Ticket can be closed if :
- [ ] all menu responses are working from the "formal research pilot" pop-up menu. This is the pop-up appears when you press the purple "Formal Testing" button on the Profile page of a user who is not a formal tester.
-[ ] all links on the Resources page still work a expected (opens a browser to dropbox, youTube, or BITS Lab wordpress)

Appropriate Formal Research Pilot menu responses are: 
**No:** Closes menu. Displays dialog reading "If you decide later that you want to be a formal tester...."
**Visit Website:** Opens browser to the BITS Lab wordpress page titled "Participate in staRt pilot testing"
**Yes:** Closes menu. Displays dialog box prompting you to enter a code from BITS lab.

**Closed** 2019-11-14 22:40 UTC
Labels: has-QA-note, v3.0.2
