### ISSUE TITLE
Check out randomization processes in Practice-Directive:

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#354] opened 2019-08-02 21:44 UTC
Randomization by Activity should be: 

Quizzes:
- [x] qzSW: random order without replacement
- [x] qzLW: random order without replacement
- [x] qzSyll: no randomization

Quests:
- [x] qtWord and qtSyll: Random order without replacement until run out of words, then repeat ("shuffled cyclic presentation")

**Comment by tarabyun** [comment] 2019-08-06 22:20
Behavior of qtSyll should be same as qtWord. Thanks!

**Comment by helencarey** [comment] 2019-09-09 20:43
@WillHaack or @tarabyun  Is there an easy way for Twylah to test the "shuffled cyclic presentation" improvement?  If so, could you write a brief QA note for her. (describe what she should try, + what we expect will happen)

**Comment by Tjc10** [comment] 2019-09-15 21:24
User "TestRandom" created and tested as outlined above (version 3.0.12).  Ratings downloaded and sent to Tara via Slack.  

*Note: While testing syllable Quest mode and select only ONE /r/ variant "ree" number of trials = 100, click through the 100 trials, scoring all words as incorrect --- while testing this scenario, I was kicked out of the app (i.e. app closed out on itself) and I had to re-enter and complete this a second time. Now both uploads attempts are showing up as upload *unsuccessful*.  When I try to upload from the "Recordings" section under the profile, the screen says "uploading" but it won't upload.  Final status of these two attempts is upload "unsuccessful."  
**Note Also: While attempting the same scenario described above (this time with the syllable "ear"), the screen froze after one token. I exited and had to re-start this session ---- but this session resumed right where I left off.  No other glitches.  Upload successful.

**Comment by WillHaack** [comment] 2019-09-15 21:47
Is there a way to reproduce the bug that knocked you out of the app? I think this behavior has occurred before (specifically in formal sessions) where the app is in a bugged state upon return after the app had closed mid session.

**Comment by tarabyun** [comment] 2019-09-19 16:37
I took a look at the ratings files generated by Twylah's testing. For Quiz sessions, shuffled-cyclic presentation appears to be working per specifications, with except for one minor bug: the first word is occasionally presented twice. I can share one of the affected json files on Slack.

**Comment by tarabyun** [comment] 2019-09-19 16:45
In the Quest session type, it appears that presentation is cyclic but NOT shuffled, i.e., items are presented in the same order each time. Here's an example where the order is always roo-roh-rah (note that the bug where the first item is presented twice is in effect here as well, so it applies to Quest as well as Quiz sessions).

![image](https://user-images.githubusercontent.com/16907239/65263763-3eee2c00-dadb-11e9-9e5b-8d5f424290fe.png)

**Comment by WillHaack** [comment] 2019-09-19 17:11
Acknowledge the above. The word appearing twice in the front is certainly a bug. I thought that the described behavior was the intended behavior (it shuffles once, and then it is cyclic) but this clarifies my misunderstanding and i'll put a commit to fix it shortly.

**Comment by WillHaack** [comment] 2019-09-24 16:51
@tarabyun As I mentioned in slack the same word appearing twice in the beginning comes from spamming the rating button very quickly while the page is still loading. This should be fixed, but it is not something that should happen with real app use, so I'm going to put it off for another version.

**Comment by WillHaack** [comment] 2019-09-24 16:57
Should be fixed with https://github.com/ByunLab/staRt-ionic/pull/388/commits/06c06d263a72be780dc4f5a14c16f5fc4e16bde0

**Comment by Tjc10** [comment] 2019-09-25 18:31
User "TestRandom2" created and tested as outlined above (version 3.0.2). This time no glitches occurred.  I was not kicked out of any of the test scenarios (as happened last time during "TestRandom" testing).  All uploads were also successful.  No errors to report here either.
NOTE: Tara, I did not do the Ratings download.  Is this needed again? Send to Tara via Slack?

**Closed** 2019-09-25 19:35 UTC
Labels: v3.0.0

**Comment by tarabyun** [comment] 2019-09-26 13:50
@Tjc10, it would be great if you could re-download the ratings files for the Quest session type only so I can check that the latest version shows the desired behavior.
