### ISSUE TITLE
[Bug] Test Probe requires 3 ratings each time

### ISSUE THREAD

**Issue by gsuthers** [ByunLab/staRt-ionic#89] opened 2017-02-20 17:55 UTC
When in Test Probe, every time you try to rate a word you have to do it three times before it works.

**Comment by tarabyun** [comment] 2017-02-21 20:30
Aha, this is a feature not a bug--each item is supposed to be presented 3 consecutive times in syllable practice. This is true of syllable practice only. Since this is causing a lot of confusion, maybe we could incorporate something in the display that indicates that it is advancing to a new item each time? The instructions for clinicians will clearly state that syllable practice should elicit 3 repetitions of each item, but I can certainly imagine people overlooking that.

**Comment by starakaj** [comment] 2017-02-24 14:24
Sounds reasonable. Does something like "Word/Syllable 4 of 100" sound good? I'm going to make a separate ticket for that and close this one out.

**Closed by starakaj** 2017-02-24 14:24 UTC
Labels: bug
